#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8762
#spring:
#  application:
#    name: service-zuul
#zuul:
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 60000
#  routes:
#    #路由转发
#    api-basicS:
#      path: /api-basicS/**
#      url: http://localhost:8764
##  重定向时隐藏真实端口地址
#  add-host-header: true
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000