
spring:
  application:
    name: zuul-config-server
  cloud:
    config:
      server:
        git:
          username:
          password:
          uri: https://github.com/CarIdentification/car-config
          search-paths: config
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
