
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          username:
          password:
          uri: https://github.com/CarIdentification/car-config.git
          search-paths: config
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://119.29.208.119:8761/eureka/
server:
  port: 8760

